
server:
  port: 7777

spring:
  datasource:
    name: coffee-db
    url: jdbc:h2:mem:coffee-db
    username: admin
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        ddl-auto: none
  h2:
    console:
      enabled: true